1. Write a Python program to sum all the items in a list.

In [ ]:
l=[2,3,7,5,10,45]
res=0
for i in l:
  res=res+i

print(res)

72

2. Write a Python program to get the largest number from a list.

In [ ]:
l1=[2,301,7,5,100,45]
h=max(l)
print(h)

45

3. Write a Python program to count the number of strings from a given list of strings. The string length is 2 or more and the first and last characters are the same.

```
Sample List : ['abc', 'xyz', 'aba', '1221']
Expected Result : 2
```

In [ ]:
l2=['abcbc', 'wxyz', 'abacd', '1221','fcca','malayalam','aa']
r1=len(l2)
print('The number of strings in the list are: ',r1)

print('The required strings are: ')
[i for i in l2 if (len(i) >= 2 and i[-1] == i[0])]

The number of strings in the list are:  7
The required strings are:

['1221', 'malayalam', 'aa']

4. Write a Python program to remove duplicates from a list.

In [ ]:
l3=['a',2,'v','a',5,7,2]
result=set(l)
list(result)

[2, 3, 5, 7, 10, 45]

5. Write a Python program to check if a list is empty or not.

In [ ]:
l4=[]
if not l2:
  print('The list is empty')

6. Write a Python program to filter the list if the length of the character is < 4

```
Sample List : ['abc', 'xyz', 'aba', '1221']
Expected Result: ['abc', 'xyz', 'aba']
```

In [ ]:
l5=['abcbc', 'wxy', 'acd', '121','fcca','malayalam','aa']
[i for i in l5 if len(i)<4]

['wxy', 'acd', '121', 'aa']

7.Write a Python program to find the second largest number in a list.

In [ ]:
l6=[2,301,7,5,10,45]
l6.sort()
print(l6[-2])

45

8. Write a Python program to reverse a list at a specific location.

In [ ]:
a=int(input('enter the location'))
l=[1,5,3,78,21,18,36,10]
if (a<=7):
  l1=l[:a]
  l2=l[a:]
  l2r=l2[::-1]
  lr=l1+l2r
  print('the required list is: ',lr)

else:
  print('enter a value within the limit')
  quit()

9. Write a Python program to check if a list is a palindrome or not. Return true otherwise false.

In [ ]:
l8=input('please enter the word to be checked')
l8r=l8[::-1]
if (l8==l8r):
  print('the string is paliandrome')
else:
  print('the string is not paliandrome')

10. Write a Python a program to find the union and intersection of two lists.

In [ ]:
l9=['ab',1,8,6,'ce','abc',18]
l10=[18,36,'acd','ce',45,8]

s1=set(l9)
s2=set(l10)

x1=s1.union(s2)
x2=s1.intersection(s2)

print('the union of the two lists = ',list(x1))
print('the intersection of the two lists = ',list(x2))

11.Write a Python script to sort (ascending and descending) a dictionary by value

In [ ]:
birthyears = {
    'Eshan': 2021,
    'Amin' : 2019,
    'Adarsh': 1996,
    'Aljo' : 1999,
    'Aiswarya': 1995,
    'shahanas': 1994
}
sort = sorted(birthyears.items(), key=lambda x:x[1])
sortdict=dict(sort)
print(sortdict)

12. Write a Python script to check whether a given key already exists in a dictionary.

In [ ]:
hundreds = {
    'Sachin' : 49,
    'Virat' : 50,
    'Rohit' : 31,
    'Ponting' : 30,
    'Jayasurya' : 28
}

x = input('Enter the key to search: ')

if x in hundreds.keys():
  print('The key already exist')

else:
  print('The key does not exist')

13.Write a Python program to sum all the values in a dictionary.

In [ ]:
hundreds = {
    'Sachin' : 49,
    'Virat' : 50,
    'Rohit' : 31,
    'Ponting' : 30,
    'Jayasurya' : 28
}


s = sum(hundreds.values())
print(f'The sum of the values is: {s}')

14.Write a Python program to create a dictionary with a number and its corresponding square from 1 to input number. And also check if the input number is less than 10

```
Eg:
Input : 3
Output : {1:1, 2:4, 3:9}
```

In [ ]:
k=int(input('enter the number: '))
{i:i*i for i in range(1,k+1)}

15.Write a Python program to sort a given dictionary by key.

In [ ]:
birthyears = {
    'Eshan': 2021,
    'Amin' : 2019,
    'Adarsh': 1996,
    'Aljo' : 1999,
    'Aiswarya': 1995,
    'shahanas': 1994
}

sort = sorted(birthyears.items())
print(dict(sort))

16.  Write a Python program to create a dictionary from a string.

```
Note: Track the count of the letters from the string.
Sample string : 'learnpython'
Expected output: {'l': 1, 'e': 1, 'a': 1, 'r': 1, 'n': 2, 'p': 1, 'y': 1, 't': 1, 'h': 1, 'o': 1}

```

In [ ]:
s = input('enter the string: ')
{i:s.count(i) for i in s}

17. Write a Python program to get the top three items in a shop.

```
Sample data: {'item1': 45.50, 'item2':35, 'item3': 41.30, 'item4':55, 'item5': 24}

Expected Output:
item4 55
item1 45.5
item3 41.3
```

In [1]:
fruits = {
    'apple' : 150,
    'banana' : 40,
    'Dragon fruit' : 300,
    'Grapes' : 100,
    'Orange' : 60,
    'Anar' : 200,
    'Strawberry' : 350,
    'Pineapple' : 80
}

sortfruits = sorted(fruits.items(), key=lambda x:x[1], reverse=True)

for i in range (3):
  print(sortfruits[i])

('Strawberry', 350)
('Dragon fruit', 300)
('Anar', 200)